name: test
on:
  workflow_dispatch:
  
jobs:
  print:
    runs-on: self-hosted
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: print
      run: |
        cat index.html
